export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_AGREEMENT = 'SAVE_AGREEMENT';
export const CREATE_AGREEMENT = 'CREATE_AGREEMENT';
